[package]
name = "speederboard"
version = "0.1.0"
edition = "2021"

[dependencies]
tower-http = { version = "0.4", default-features = false, features = ["compression-full", "decompression-full"] }
reqwest = { version = "0.11.18", features = ["rustls-tls", "stream", "trust-dns"], default-features = false }
sqlx = { version = "0.7", features = ["macros", "postgres", "tls-rustls", "runtime-tokio"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal", "tracing"] }
redis = { version = "0.23", features = ["aio", "connection-manager"] }
axum = { version = "0.6", features = ["http2", "headers", "macros"] }
axum-extra = { version = "0.7", features = ["cookie", "multipart"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1", features = ["derive"] }
markdown = "1.0.0-alpha.12"
deadpool-redis = "0.12"
serde_json = "1"
dotenvy = "0.15"
thiserror = "1"
tracing = "0.1"
argon2 = "0.5"
tera = "1.19"
envy = "0.4"
rand = "0.8"
rayon = "1"

[profile.dev.package.argon2]
opt-level = 3
