[package]
name = "simpleinterpolation"
version = "0.1.0"
edition = "2021"

[features]
default = []
value = ["dep:serde_json"]

[dependencies]
serde_json = { version = "1", default-features = false, optional = true }