name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SQLX_OFFLINE: true

permissions:
  packages: write
  contents: read

jobs:
  check:
    uses: ./.github/workflows/check.yml

  build:
    runs-on: ubuntu-latest
    needs: [check]
    strategy:
      fail-fast: true
      matrix:
        arch: [aarch64, x86_64]
    steps:
      - name: Check out code into the proper directory
        uses: actions/checkout@v3

      - name: Install cargo
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.arch }}-unknown-linux-musl

      - name: Cache rust
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.arch }}

      - name: Download musl development toolchain for ${{ matrix.arch }}
        run: curl -fsSl https://musl.cc/${{ matrix.arch }}-linux-musl-cross.tgz --output ${{ matrix.arch }}-linux-musl-cross.tgz

      - name: Set up musl-${{ matrix.arch }} development toolchain
        run: tar -xvf ./${{ matrix.arch }}-linux-musl-cross.tgz

      - name: Build executables
        env:
          TARGET_CC: ${{ github.workspace }}/${{ matrix.arch }}-linux-musl-cross/bin/${{ matrix.arch }}-linux-musl-cc
          TARGET_AR: ${{ github.workspace }}/${{ matrix.arch }}-linux-musl-cross/bin/${{ matrix.arch }}-linux-musl-ar
          RUSTFLAGS: -C linker=${{ github.workspace }}/${{ matrix.arch }}-linux-musl-cross/bin/${{ matrix.arch }}-linux-musl-cc
        run: cargo b --release --target ${{ matrix.arch }}-unknown-linux-musl

      - name: Upload executables
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}-executables
          path: |
            target/${{ matrix.arch }}-unknown-linux-musl/release/speederboard

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Correct env
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Check out code into the proper directory
        uses: actions/checkout@v3

      - name: Download ARM executables
        uses: actions/download-artifact@v3
        with:
          name: aarch64-executables
          path: ./arm64-executables

      - name: Download x86 executables
        uses: actions/download-artifact@v3
        with:
          name: x86_64-executables
          path: ./amd64-executables

      - name: Mark programs as executable
        run: chmod +x ./*executables/*

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: ghcr.io/${{ env.REPO }}:latest
          platforms: linux/arm64,linux/amd64
  deploy:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - name: Notify bot of updates
        run: "curl --max-time 30 -H 'Authorization: Bearer ${{ secrets.RESTART_TOKEN }}' https://xpd-hooks.valk.sh/update/pastebot"

