name: Cargo Check
on:
  pull_request:
    paths:
      - src/**
      - subcrates/**
      - migrations/**
      - .sqlx/**
      - .github/**
      - build.rs
      - Cargo.toml
      - Cargo.lock
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      minio:
        image: minio/minio:latest
        options: >- 
          --entrypoint="" 
          minio/minio:latest 
          /bin/bash -c 'mkdir /data/test && /usr/bin/minio server --address 0.0.0.0:9000 /srv/minio/data'
        ports:
          - 9000:9000
      redis:
        image: redis:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install various dependencies
        run: apt update -y && apt install pkg-config curl build-essential openssl libssl-dev git python3 -y

      - name: Safelist all git directories
        run: git config --global safe.directory '*'

      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: Cache Packages
        uses: Swatinem/rust-cache@v2
        with:
          key: "check"

      - name: Check formatting
        run: cargo fmt --check

      - name: Check dev build
        run: cargo clippy

      - name: Check prod build
        run: cargo clippy --no-default-features

      - name: Generate test data
        run: python3 ./src/fixtures/generate/all.py

      - name: Run tests
        run: cargo test
        env:
          DATABASE_URL: postgres://postgres:postgres@postgres/postgres
