name: Cargo Check
on:
  pull_request:
    paths:
      - src/**
      - subcrates/**
      - .sqlx/**
      - .github/**
      - Cargo.toml
      - Cargo.lock
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      minio:
        image: minio/minio:latest
        options: >- 
          --entrypoint="" minio/minio:latest /bin/bash -c 'mkdir /data/test && /usr/bin/minio'
      redis:
        image: redis:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Packages
        uses: Swatinem/rust-cache@v2
        with:
          key: "check"

      - name: Check formatting
        run: cargo fmt --check

      - name: Check dev build
        run: cargo clippy

      - name: Check prod build
        run: cargo clippy --no-default-features

      - name: Run tests
        run: cargo test
        env:
          DATABASE_URL: postgres://postgres:postgres@postgres/postgres
          REDIS_URL: redis://127.0.0.1/
          ROOT_URL: http://127.0.0.1:8080
          USER_CONTENT_URL: http://127.0.0.1:9000/speederboard/
          STATIC_URL: http://127.0.0.1:8000/
          LOG: trace
          S3_PATH_STYLE: true
          S3_ENDPOINT: http://127.0.0.1:9000/
          S3_REGION: us-east-1
          S3_BUCKET_NAME: speederboard
          S3_ACCESS_KEY: minioadmin
          S3_SECRET_KEY: minioadmin