name: Windows dev build
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - subcrates/**
      - migrations/**
      - .sqlx/**
      - .github/**
      - Cargo.toml
      - Cargo.lock
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out code into the proper directory
        uses: actions/checkout@v4

      - name: Install cargo
        uses: dtolnay/rust-toolchain@stable

      - name: Cache rust
        uses: Swatinem/rust-cache@v2
        with:
          key: "windows"

      - name: Build executable
        run: cargo build --release

      - name: Upload executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: |
            target/release/speederboard.exe

      - name: Upload executable to CDN
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: r2 object put -f target/release/speederboard.exe speederboard/executables/speederboard.exe