name: CI
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - migrations/**
      - templates/**
      - .sqlx/**
      - .github/**
      - Cargo.toml
      - Cargo.lock
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  check:
    uses: ./.github/workflows/check.yml

  build:
    runs-on: windows-latest
    needs: [check]
    steps:
      - name: Check out code into the proper directory
        uses: actions/checkout@v3

      - name: Install cargo
        uses: dtolnay/rust-toolchain@stable

      - name: Cache rust
        uses: Swatinem/rust-cache@v2

      - name: Build executable
        run: cargo build --release

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: |
            target/release/speederboard.exe