name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SQLX_OFFLINE: true

permissions:
  packages: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the proper directory
        uses: actions/checkout@v3

      - name: deploy
        uses: cloudflare/wrangler-action@3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }
          workingDirectory: "cdn-upload-worker"
          command: publish --env staging