name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  worker-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the proper directory
        uses: actions/checkout@v3

      - name: deploy
        uses: cloudflare/wrangler-action@3.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "cdn-upload-worker"
          command: publish --env staging