name: Deploy s3 upload worker
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  worker-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the proper directory
        uses: actions/checkout@v3

      - name: deploy prod
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "cdn-upload-worker"
          command: deploy --config wrangler.prod.toml

      - name: deploy dev
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: "cdn-upload-worker"
          command: deploy --config wrangler.toml